INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1008', '2', 'VnPortal');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1009', '2', 'Tổ phần mềm khối chính quyền');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1001', '2', 'I-OFFICE');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1002', '3', 'HIS');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1003', '3', 'VnEdu');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1004', '3', 'HIS (H-SOFT)');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1005', '4', 'ÐH SXKD');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1006', '1', 'Ban Giám Đốc');
INSERT INTO "NHOM_TAI_KHOAN" VALUES ('1007', '5', 'TT CNTT');