INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('1', 'Mới', null);
INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('2', 'Đang xử lý', null);
INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('3', 'Hoàn thành', null);
INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('4', 'Tạm hoãn', null);
INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('6', 'Hủy', null);
INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('7', 'Không thể thực hiện', null);
INSERT INTO "TRANG_THAI_CONG_VIEC" VALUES ('5', 'Hoãn', null);